type: tracking
start: 0
end: 2000 #1650
stop: 0
ctx_path: /home/ubuntu/BFM-Zero-23DOF/results/bfmzero-isaac-23dof-new/tracking_inference/zs_25.pkl
gamma: 0.8  # discount factor for context averaging
window_size: 3  # number of frames to average
